language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - python setup.py install
  - pip install coveralls
script:
  - python setup.py install
  - coverage run --source=djvubind setup.py test
after_success:
  - coveralls --verbose
